image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: Always
  repository: ghcr.io/fitnest-code/storage-backend
  tag: production-25d901c
networkPolicy:
  allowedServices:
    - user-backend
    - catalog-backend
    - notifications-backend
    - fitness-plan-backend
    - payment-backend
    - support-backend
  enabled: true
replicaCount: 1
service:
  port: 9090
  type: ClusterIP
vaultEnv: production
