image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: Always
  repository: ghcr.io/fitnest-code/storage-backend
  tag: production-b915335
networkPolicy:
  allowedServices:
    - user-backend
    - catalog-backend
    - notifications-backend
    - fitness-plan-backend
    - payment-backend
    - support-backend
  enabled: true
replicaCount: 1
service:
  port: 8080
  grpcPort: 9090
  type: ClusterIP
vaultEnv: production
resources:
  requests:
    cpu: 100m
    memory: 192Mi
  limits:
    cpu: 1000m
    memory: 384Mi
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "false"
  instrumentation.opentelemetry.io/inject-nodejs: "fitnest-instrumentation"
